export type RolesString =
  | 'Gestion'
  | 'Administrateur'
  | 'Animateur'
  | 'Modérateur'
  | 'Graphiste'
  | 'Helpeur'
  | 'Radio'
  | 'Assistant EC'
  | 'Event Builder'
  | 'Wired Builder'
  | 'Croupier'
  | 'Animateur Casino'
  | 'Role Play'
  | 'everyone';
